local_name: workbench.service.project # 本地服务名
k8s_service_name: workbench.project # k8s 服务名
runmode: debug                 # 开发模式, debug, release, test 部署时环境变量覆盖
tracing:
  jager: localhost:6831 # opentracing 
db:  # DB 配置 部署时环境变量覆盖
  name: workbench_test
  addr: rm-uf6zra36x1613y5r8oo.mysql.rds.aliyuncs.com:3306
  username: workbench_test
  password: muxiworkbench
redis:
  addr: 127.0.0.1:6379
  password: ""
trashbin:
  expired: 1 # 1 天
  tidy_time: 24 # hour
