kind: pipeline
type: docker
name: workbench-be

clone:
  depth: 1

steps:
  - name: build user image
    image: plugins/docker # 构建docker镜像专用镜像
    when:
      ref:
      - refs/tags/release-user-*
    volumes:
      - name: dockersock # 挂载下面定义的Volumn
        path: /var/run/docker.sock # 与宿主机用同一docker
    settings: # plugins/docker用到的相关配置
      username:
        from_secret: docker_user # alicloud指定的docker hub的用户名(前面配置)
      password:
        from_secret: docker_password # alicloud指定的docker hub的密码(前面配置)
      repo: registry-vpc.cn-hangzhou.aliyuncs.com/muxi_site/workbench_user  #要推送docker地址
      registry: registry.cn-hangzhou.aliyuncs.com # 使用的docker hub地址
      tags: ${DRONE_TAG} # docker的tag值, 默认每次加1
      build_args:
        - service_name=user
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock