local_name: workbench.service.user # 本地服务名
k8s_service_name: workbench.user-be # k8s 服务名
runmode: debug                 # 开发模式, debug, release, test 部署时环境变量覆盖
jwt_secret: workbenchmuxihacker
tracing:
  jager: localhost:6831 # opentracing
db:  # DB 配置 部署时环境变量覆盖
  name: workbench_test
  addr: rm-bp1pkcz9y269h30fm5o.mysql.rds.aliyuncs.com:3306
  username: workbench_test
  password: Muxistudio304
auth_server:  # auth 内网
  host: pass.muxi-tech.xyz
  client_id: 51f03389-2a18-4941-ba73-c85d08201d42
  client_secret: 7d52480f-730d-45a1-99cc-1397985ebe0e
token:
  expired: 30 # 过期时间（天）
