local_name: workbench.service.team # 本地服务名
k8s_service_name: workbench.team # k8s 服务名
runmode: debug                 # 开发模式, debug, release, test 部署时环境变量覆盖
tracing:
  jager: localhost:6831 # opentracing
db:  # DB 配置 部署时环境变量覆盖
  name: workbench_test
  addr: rm-bp1pkcz9y269h30fm5o.mysql.rds.aliyuncs.com
  username: uworkbench_test
  password: Muxistudio304
redis:
  addr: 127.0.0.1:6379
  password:
aes:
  sercet_key: 